baseURL: https://dannolte.netlify.app/
languageCode: en-us
title: The Hand that Mocked Them
theme: hugo-theme-cactus
copyright: Dan Nolte
disqusShortname: example
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Writings
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: About
      url: /about
      weight: 4
    - name: Resume
      url: /resume/test.pdf
      weight: 4
markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
params:
  colortheme: light
  comments:
    enabled: no
    engine: disqus
  dateFormat: '2006-01-02'
  description: Hi! 
  googleAnalyticsAsync: yes
  mainSection: posts
  postsOnHomePage: 5
  projectsUrl: https://github.com/gohugoio
  rss: yes
  show_updated: no
  showAllPostsOnHomePage: no
  showProjectsList: yes
  showReadTime: no
  social:
    - link: https://github.com/dnolter959
      name: github
    - link: https://www.linkedin.com/in/dansnolte/
      name: linkedin
    - link: dnolte220@gmail.com
      name: email
    - link: https://twitter.com/dnolter959
      name: twitter
  tagsOverview: yes
